// 로컬 개발용 목업 데이터 — Supabase 미설정 시 data.ts가 사용.
// 실제 RSS 수집/요약 결과와 같은 형태(Article/YoutubeVideo)로 채워 UI를 그대로 볼 수 있게 한다.
// category_id는 0001_init.sql 시드 순서: 1 정치 · 2 경제 · 3 사회 · 4 IT·과학 · 5 국제 · 6 스포츠 · 7 연예·문화
import type { Article, YoutubeVideo, Topic } from "@shared/types";

const D = "2026-06-11";
const stamp = `${D}T08:00:00+09:00`;

function article(
  id: number,
  category_id: number,
  hhmm: string,
  ai_headline: string,
  title: string,
  summary_short: string,
  summary_bullets: string[],
  body_full: string,
  opts: { is_featured?: boolean; thumbnail_url?: string | null } = {},
): Article {
  const published_at = `${D}T${hhmm}:00+09:00`;
  return {
    id,
    source_id: `mock-${6500000 + id}`,
    title,
    original_url: `https://www.nocutnews.co.kr/news/${6500000 + id}`,
    body_full,
    summary_short,
    summary_bullets,
    ai_headline,
    thumbnail_url: opts.thumbnail_url ?? null,
    category_id,
    published_at,
    status: "published",
    source_type: "rss",
    is_featured: opts.is_featured ?? false,
    created_at: stamp,
    updated_at: stamp,
  };
}

const RAW_ARTICLES: Article[] = [
  article(
    1,
    1,
    "18:42",
    "여야, 추경 규모 협상 막판 진통",
    "여야, 추경 규모 두고 막판 협상…본회의 일정 불투명",
    "여야가 올해 추가경정예산 규모를 두고 막판 협상에 들어갔다. 정부안과 야당 요구안의 격차가 좁혀지지 않으면서 이번 주 본회의 처리 여부가 불투명해졌다. 양측은 민생 지원 항목에서는 공감대를 이뤘으나 재원 마련 방식에서 이견을 보이고 있다.",
    ["정부안과 야당안 규모 격차 핵심 쟁점", "민생 지원 항목은 일부 합의", "본회의 처리 시점 이번 주 넘길 수도"],
    "여야는 11일 국회에서 추가경정예산안 협상을 이어갔다. 여당은 정부가 제출한 원안 처리를 요구한 반면, 야당은 민생 지원 확대를 위한 증액을 주장했다. 양측은 소상공인 지원과 취약계층 대책 등 일부 항목에서는 의견 접근을 이뤘지만, 국채 발행을 통한 재원 조달 방식을 두고 평행선을 달렸다. 국회 관계자는 \"본회의 일정이 이번 주를 넘길 가능성도 배제할 수 없다\"고 말했다.",
    { is_featured: true },
  ),
  article(
    2,
    2,
    "17:55",
    "5월 소비자물가 2.1% 상승",
    "5월 소비자물가 2.1% 올라…석 달째 둔화세",
    "지난달 소비자물가 상승률이 2.1%를 기록하며 석 달 연속 둔화했다. 농산물 가격이 안정세를 보인 영향이 컸다. 다만 외식 등 개인 서비스 물가는 여전히 3%대를 유지하며 체감 물가 부담은 이어지고 있다.",
    ["5월 소비자물가 전년比 2.1% 상승", "농산물 가격 안정이 둔화 견인", "개인 서비스 물가는 3%대 지속"],
    "통계청이 발표한 5월 소비자물가동향에 따르면 소비자물가지수는 1년 전보다 2.1% 올랐다. 상승률은 3월 2.4%, 4월 2.3%에 이어 석 달째 낮아졌다. 기상 여건이 좋아지며 채소류 가격이 하락한 것이 둔화의 주된 요인으로 분석된다. 반면 외식과 보험 등 개인 서비스 부문은 3%대 상승률을 이어가 서민 체감 물가는 여전히 높다는 지적이 나온다.",
  ),
  article(
    3,
    3,
    "16:30",
    "수도권 출퇴근 광역버스 증차",
    "수도권 광역버스 출퇴근 증차…입석 대란 완화 기대",
    "국토교통부가 다음 달부터 수도권 주요 노선의 광역버스를 증차한다고 밝혔다. 출퇴근 시간대 입석 승차로 인한 안전 문제와 혼잡을 줄이기 위한 조치다. 우선 경기 남부 노선부터 단계적으로 적용된다.",
    ["다음 달부터 광역버스 단계적 증차", "출퇴근 입석·혼잡 완화 목적", "경기 남부 노선 우선 적용"],
    "국토교통부는 수도권 광역버스의 출퇴근 시간대 혼잡을 완화하기 위해 다음 달부터 주요 노선에 버스를 추가 투입한다고 11일 밝혔다. 그동안 일부 노선은 좌석이 가득 차 입석으로 운행되며 안전 우려가 제기돼 왔다. 국토부는 경기 남부 지역 노선부터 증차를 시작해 수요가 많은 구간으로 확대할 계획이다.",
  ),
  article(
    4,
    4,
    "15:10",
    "국산 AI 반도체 데이터센터 첫 도입",
    "국산 AI 반도체, 공공 데이터센터 첫 상용 도입",
    "국내 기업이 개발한 AI 반도체가 공공 데이터센터에 처음으로 상용 도입된다. 그동안 해외 제품에 의존하던 AI 인프라의 국산화 신호탄으로 평가된다. 정부는 향후 공공 부문 도입을 단계적으로 늘릴 방침이다.",
    ["국산 AI 반도체 공공 데이터센터 첫 적용", "해외 의존 AI 인프라 국산화 전환점", "정부, 공공 도입 단계적 확대 방침"],
    "과학기술정보통신부는 국내 기업이 자체 설계한 AI 추론용 반도체가 공공 데이터센터에 상용 도입된다고 밝혔다. 그간 국내 AI 연산 인프라는 대부분 해외 GPU에 의존해 왔다. 이번 도입은 전력 효율과 비용 측면에서 국산 칩의 경쟁력을 검증하는 계기가 될 전망이다. 정부는 실증 결과를 토대로 공공 부문 도입 범위를 넓혀갈 계획이다.",
  ),
  article(
    5,
    5,
    "14:20",
    "주요국 중앙은행 금리 동결 잇따라",
    "주요국 중앙은행 잇단 금리 동결…인하 시점 저울질",
    "미국과 유럽의 주요 중앙은행이 잇따라 기준금리를 동결했다. 물가 둔화 흐름은 확인됐지만 인하를 서두르기엔 이르다는 신중론이 우세했다. 시장은 하반기 인하 가능성에 무게를 두고 있다.",
    ["미·유럽 중앙은행 기준금리 동결", "물가 둔화에도 인하엔 신중", "시장은 하반기 인하 전망"],
    "미국 연방준비제도와 유럽중앙은행이 이번 통화정책 회의에서 기준금리를 현 수준으로 유지했다. 물가 상승세가 진정되고 있으나 목표치까지는 여유가 더 필요하다는 판단에서다. 통화당국은 추가 지표를 확인한 뒤 인하 시점을 결정하겠다는 입장이다. 금융시장에서는 하반기 중 금리 인하가 시작될 것이라는 기대가 형성되고 있다.",
  ),
  article(
    6,
    6,
    "13:05",
    "프로야구 선두 다툼 최종전까지",
    "프로야구 선두 경쟁 치열…한 경기 차 초접전",
    "프로야구 정규시즌 선두 다툼이 한 경기 차로 좁혀지며 막판까지 안갯속이다. 상위 두 팀이 나란히 연승을 달리면서 순위 경쟁이 시즌 최종전까지 이어질 전망이다.",
    ["선두-2위 승차 한 경기로 축소", "상위권 두 팀 동반 연승", "순위 다툼 최종전까지 지속 전망"],
    "프로야구 정규시즌 종반 선두 경쟁이 뜨겁다. 선두 팀과 2위 팀의 승차가 한 경기로 좁혀지면서 매 경기 결과에 따라 순위가 뒤바뀌는 상황이 이어지고 있다. 두 팀 모두 최근 상승세를 타고 있어 정규시즌 우승 향방은 막판까지 가려지지 않을 것으로 보인다.",
  ),
  article(
    7,
    7,
    "11:40",
    "국내 영화 칸 주요 부문 수상",
    "한국 영화, 칸영화제 주요 부문 수상…호평 이어져",
    "한국 영화가 올해 칸영화제 주요 부문에서 상을 받으며 다시 한 번 세계 무대에서 존재감을 입증했다. 현지 평단은 연출과 연기 모두에 높은 점수를 줬다.",
    ["한국 영화 칸 주요 부문 수상", "연출·연기 현지 평단 호평", "국내 개봉 일정도 관심"],
    "올해 칸영화제에서 한국 영화가 주요 부문 수상의 영예를 안았다. 현지 언론과 평단은 작품의 섬세한 연출과 배우들의 깊이 있는 연기를 고루 호평했다. 수상 소식이 전해지면서 국내 개봉 일정과 흥행 전망에도 관심이 쏠리고 있다.",
  ),
  article(
    8,
    3,
    "10:15",
    "장마 시작…중부 집중호우 대비",
    "이번 주 장마 시작…중부지방 집중호우 대비 당부",
    "기상청이 이번 주 후반 장마가 시작될 것으로 내다봤다. 특히 중부지방을 중심으로 시간당 강한 비가 예보돼 침수와 산사태 등 피해 예방이 필요하다.",
    ["이번 주 후반 장마 시작 전망", "중부 시간당 강한 비 예보", "침수·산사태 대비 당부"],
    "기상청은 정체전선의 영향으로 이번 주 후반부터 장마가 시작될 것으로 예상된다고 밝혔다. 중부지방을 중심으로 시간당 30㎜ 안팎의 강한 비가 내리는 곳이 있겠다. 당국은 하천 변과 저지대 침수, 비탈면 붕괴 등에 대비해 사전 점검과 안전 관리에 유의해 달라고 당부했다.",
  ),
  article(
    9,
    2,
    "09:30",
    "수출 8개월째 증가세",
    "5월 수출 8개월 연속 증가…반도체가 견인",
    "지난달 수출이 8개월 연속 늘며 회복세를 이어갔다. 반도체 수출이 큰 폭으로 증가한 것이 전체 실적을 끌어올렸다. 자동차와 선박도 호조를 보였다.",
    ["5월 수출 8개월 연속 증가", "반도체 수출 큰 폭 확대", "자동차·선박도 호조"],
    "산업통상자원부에 따르면 5월 수출액이 1년 전보다 늘며 8개월 연속 증가세를 기록했다. 인공지능 수요 확대에 힘입어 반도체 수출이 큰 폭으로 늘어난 것이 실적 개선을 주도했다. 자동차와 선박 등 주력 품목도 양호한 흐름을 보이며 무역수지 흑자 기조가 이어졌다.",
  ),
  article(
    10,
    4,
    "08:50",
    "온라인 플랫폼 개인정보 규제 강화",
    "온라인 플랫폼 개인정보 규제 강화 법안 추진",
    "정부가 온라인 플랫폼의 개인정보 처리에 대한 규제를 강화하는 법안을 추진한다. 이용자 동의 절차를 명확히 하고 위반 시 과징금을 높이는 내용이 담겼다.",
    ["플랫폼 개인정보 규제 강화 법안 추진", "이용자 동의 절차 명확화", "위반 과징금 상향"],
    "개인정보보호위원회는 대형 온라인 플랫폼의 개인정보 수집·이용에 대한 규율을 강화하는 법 개정을 추진한다고 밝혔다. 개정안에는 이용자에게 정보 처리 목적을 명확히 고지하고 동의를 받도록 하는 절차와, 위반 시 과징금을 상향하는 내용이 포함됐다. 업계는 규제 준수 비용 증가를 우려하며 의견을 제출할 예정이다.",
  ),
  article(
    11,
    1,
    "08:05",
    "지방선거 D-1년 정당별 채비 분주",
    "내년 지방선거 1년 앞으로…정당별 채비 분주",
    "내년 지방선거를 약 1년 앞두고 각 정당이 인재 영입과 공천 룰 정비에 속도를 내고 있다. 광역단체장 후보군을 둘러싼 신경전도 일찌감치 시작됐다.",
    ["지방선거 약 1년 앞으로", "정당별 인재 영입·공천 룰 정비", "광역단체장 후보 신경전 시작"],
    "내년 전국동시지방선거를 1년가량 앞두고 정치권의 움직임이 빨라지고 있다. 각 정당은 경쟁력 있는 인물 영입과 공천 방식 정비에 착수했다. 주요 광역단체장 자리를 놓고는 잠재 후보군 간 물밑 경쟁도 본격화하는 분위기다.",
  ),
  article(
    12, 6, "20:10",
    "축구대표팀, 월드컵 본선 진출 확정",
    "축구대표팀 월드컵 본선行 확정…조 1위로 통과",
    "한국 축구 국가대표팀이 월드컵 아시아 최종예선에서 조 1위로 본선 진출을 확정했다. 손흥민을 중심으로 한 공격진이 살아나며 최근 3연승을 달렸다.",
    ["월드컵 본선 진출 확정", "최종예선 조 1위 통과", "손흥민 공격 호조 3연승"],
    "한국 축구 국가대표팀이 월드컵 아시아 최종예선에서 승리하며 조 1위로 본선 진출을 확정했다. 손흥민과 이강인 등 유럽파가 주축이 된 공격진이 살아나며 팀은 최근 3연승을 기록했다. 대표팀은 본선 조 추첨 결과에 따라 전지훈련 일정을 조율할 계획이다.",
  ),
  article(
    13, 1, "19:30",
    "일부 투표소 투표용지 부족 혼란",
    "재보선 일부 투표소 투표용지 부족…유권자 항의 잇따라",
    "재보궐선거 당일 일부 투표소에서 투표용지가 부족해 유권자들이 발길을 돌리는 혼란이 빚어졌다. 선관위는 긴급 추가 배부에 나섰고 재발 방지를 약속했다.",
    ["일부 투표소 투표용지 부족", "유권자 대기·항의 발생", "선관위 긴급 배부·사과"],
    "재보궐선거가 치러진 11일 일부 투표소에서 투표용지가 일찍 소진돼 유권자들이 한동안 투표하지 못하는 상황이 발생했다. 선거관리위원회는 인근 투표소에서 용지를 긴급 이송해 배부했으며, 수요 예측 실패를 인정하고 재발 방지 대책을 마련하겠다고 밝혔다.",
  ),
  article(
    14, 2, "16:05",
    "코스피 사상 첫 3300선 돌파",
    "코스피 3300 첫 돌파…반도체·AI주 강세",
    "코스피가 장중 사상 처음으로 3300선을 넘어섰다. 반도체와 AI 관련주에 외국인 매수가 몰리며 지수를 끌어올렸다.",
    ["코스피 사상 첫 3300 돌파", "반도체·AI주 강세", "외국인 순매수 유입"],
    "코스피가 11일 장중 3300선을 사상 처음으로 돌파했다. 인공지능 반도체 수요 기대에 외국인 투자자의 매수세가 반도체 대형주에 집중되며 지수 상승을 이끌었다. 증권가는 단기 과열 우려와 함께 실적 시즌 결과가 추가 상승의 분수령이 될 것으로 봤다.",
  ),
  article(
    15, 4, "14:40",
    "스페이스X 스타십 궤도 시험 성공",
    "스페이스X 스타십, 궤도 비행·회수 시험 성공",
    "스페이스X가 차세대 우주선 스타십의 궤도 비행과 1단 추진체 회수 시험에 성공했다. 위성 발사 비용 절감과 심우주 탐사의 전환점으로 평가된다.",
    ["스타십 궤도 비행 성공", "1단 추진체 회수 성공", "발사 비용 절감 기대"],
    "스페이스X가 대형 우주발사체 스타십의 궤도 비행 시험에서 발사부터 1단 추진체 회수까지 주요 단계를 성공적으로 마쳤다. 회사는 재사용성을 높여 발사 단가를 크게 낮추는 것을 목표로 하고 있으며, 이번 성공으로 위성 발사와 심우주 탐사 일정에 탄력이 붙을 전망이다.",
  ),
  article(
    16, 4, "13:20",
    "엔비디아 신형 AI 가속기 공개",
    "엔비디아, 차세대 AI 가속기 공개…공급난 재현 우려",
    "엔비디아가 차세대 AI 가속기를 공개하며 성능을 크게 끌어올렸다. 수요가 폭증할 것으로 보여 다시 공급난이 빚어질 수 있다는 관측이 나온다.",
    ["엔비디아 차세대 AI 가속기 공개", "전작 대비 성능 대폭 향상", "공급난 재현 우려"],
    "엔비디아가 새 AI 가속기를 공개하고 추론·학습 성능을 전작 대비 크게 높였다고 밝혔다. 데이터센터 업계의 도입 경쟁이 예상되면서 초기 물량 확보를 둘러싼 공급난이 재현될 수 있다는 전망이 나온다. 국내 메모리 업체들도 고대역폭 메모리 공급 확대에 나설 것으로 보인다.",
  ),
  article(
    17, 1, "11:50",
    "이재명 정부 첫 민생대책 발표",
    "이재명 정부, 첫 민생종합대책 발표…내수 진작 초점",
    "이재명 정부가 출범 후 첫 민생종합대책을 내놨다. 소상공인 지원과 내수 진작에 초점을 맞췄으며, 여당은 입법 뒷받침을 예고했다.",
    ["이재명 정부 첫 민생대책", "소상공인 지원·내수 진작", "여당 입법 뒷받침 예고"],
    "이재명 정부가 출범 이후 처음으로 민생종합대책을 발표했다. 소상공인·자영업자 지원과 내수 진작을 핵심으로 하며, 재원 조달 방안도 함께 제시됐다. 더불어민주당은 관련 입법을 신속히 처리하겠다고 밝힌 반면, 국민의힘은 재정 부담을 지적하며 신중론을 폈다.",
  ),
  article(
    18, 7, "10:30",
    "뉴진스 새 앨범 글로벌 차트 석권",
    "뉴진스 새 미니앨범, 글로벌 차트 정상",
    "뉴진스가 새 미니앨범으로 주요 글로벌 음원 차트 정상에 올랐다. 타이틀곡은 공개 직후 국내외 차트를 휩쓸며 흥행을 이어가고 있다.",
    ["뉴진스 새 미니앨범 발매", "글로벌 차트 정상 등극", "타이틀곡 국내외 석권"],
    "뉴진스가 발표한 새 미니앨범이 공개와 동시에 주요 글로벌 음원·앨범 차트 상위권에 진입했다. 타이틀곡은 국내 음원 차트와 해외 스트리밍 차트에서 좋은 반응을 얻으며 흥행을 이어가고 있다. 소속사는 후속 활동과 월드투어 일정을 조율 중이다.",
  ),
];

// 기사별 자동 추출 키워드(토픽 slug) — 추후 Claude 개체명 추출 결과로 대체
const ARTICLE_KEYWORDS: Record<number, string[]> = {
  1: ["chuga", "minjoo", "ppp", "han-donghoon"],
  2: ["inflation"],
  3: ["gwangyeok-bus"],
  4: ["ai-chip", "semiconductor"],
  5: ["interest-rate"],
  6: ["kbo"],
  7: ["cannes", "korean-film", "bong-joonho"],
  8: ["jangma"],
  9: ["export", "semiconductor"],
  10: ["privacy", "platform-regulation"],
  11: ["local-election", "minjoo", "ppp", "lee-jaemyung", "oh-sehoon"],
  12: ["worldcup", "son-heungmin", "lee-kangin"],
  13: ["ballot-shortage", "local-election"],
  14: ["kospi", "semiconductor", "ai"],
  15: ["spacex"],
  16: ["nvidia", "ai", "semiconductor", "ai-chip"],
  17: ["lee-government", "lee-jaemyung", "minjoo", "ppp"],
  18: ["newjeans"],
};

export const MOCK_ARTICLES: Article[] = RAW_ARTICLES.map((a) => ({
  ...a,
  // 실데이터 전엔 시드 기반 placeholder로 썸네일 자리 미리보기 (id별 고정 이미지)
  thumbnail_url: a.thumbnail_url ?? `https://picsum.photos/seed/nocut${a.id}/320/220`,
  keywords: ARTICLE_KEYWORDS[a.id] ?? [],
}));

// 관심사 토픽 목록 — 추후 topics 테이블로 대체. mention_count는 트렌딩 정렬용.
export const MOCK_TOPICS: Topic[] = [
  // 인물
  { slug: "lee-jaemyung", name: "이재명", type: "person", mention_count: 21 },
  { slug: "han-donghoon", name: "한동훈", type: "person", mention_count: 17 },
  { slug: "oh-sehoon", name: "오세훈", type: "person", mention_count: 9 },
  { slug: "kim-munsoo", name: "김문수", type: "person", mention_count: 6 },
  // 정당
  { slug: "minjoo", name: "더불어민주당", type: "party", mention_count: 23 },
  { slug: "ppp", name: "국민의힘", type: "party", mention_count: 22 },
  { slug: "reform", name: "개혁신당", type: "party", mention_count: 5 },
  { slug: "rebuilding", name: "조국혁신당", type: "party", mention_count: 4 },
  // 이슈
  { slug: "chuga", name: "추경예산", type: "issue", mention_count: 24 },
  { slug: "local-election", name: "지방선거", type: "issue", mention_count: 19 },
  { slug: "inflation", name: "물가", type: "issue", mention_count: 18 },
  { slug: "semiconductor", name: "반도체", type: "issue", mention_count: 16 },
  { slug: "export", name: "수출", type: "issue", mention_count: 13 },
  { slug: "ai-chip", name: "AI반도체", type: "issue", mention_count: 12 },
  { slug: "interest-rate", name: "기준금리", type: "issue", mention_count: 11 },
  { slug: "jangma", name: "장마", type: "issue", mention_count: 10 },
  { slug: "privacy", name: "개인정보보호", type: "issue", mention_count: 8 },
  { slug: "platform-regulation", name: "플랫폼 규제", type: "issue", mention_count: 7 },
  { slug: "gwangyeok-bus", name: "광역버스 증차", type: "issue", mention_count: 6 },
  { slug: "korean-film", name: "한국영화", type: "issue", mention_count: 6 },
  { slug: "realestate", name: "부동산", type: "issue", mention_count: 5 },
  // 스포츠
  { slug: "kbo", name: "프로야구", type: "sports", mention_count: 14 },
  { slug: "son-heungmin", name: "손흥민", type: "sports", mention_count: 12 },
  { slug: "lee-kangin", name: "이강인", type: "sports", mention_count: 8 },
  { slug: "kim-minjae", name: "김민재", type: "sports", mention_count: 6 },
  // 연예
  { slug: "cannes", name: "칸영화제", type: "celebrity", mention_count: 11 },
  { slug: "bong-joonho", name: "봉준호", type: "celebrity", mention_count: 9 },
  { slug: "bts", name: "BTS", type: "celebrity", mention_count: 15 },
  { slug: "newjeans", name: "뉴진스", type: "celebrity", mention_count: 10 },
  { slug: "iu", name: "아이유", type: "celebrity", mention_count: 9 },
  // 샘플(지금 뜨는) 추가 토픽
  { slug: "ai", name: "AI", type: "issue", mention_count: 30 },
  { slug: "lee-government", name: "이재명 정부", type: "issue", mention_count: 26 },
  { slug: "worldcup", name: "월드컵", type: "sports", mention_count: 22 },
  { slug: "nvidia", name: "엔비디아", type: "issue", mention_count: 20 },
  { slug: "kospi", name: "코스피", type: "issue", mention_count: 17 },
  { slug: "spacex", name: "스페이스X", type: "issue", mention_count: 16 },
  { slug: "ballot-shortage", name: "투표용지 부족 사태", type: "issue", mention_count: 14 },
];

export const MOCK_VIDEOS: YoutubeVideo[] = [
  {
    id: 1,
    video_id: "mockvid001",
    title: "[노컷 라이브] 오늘의 주요 뉴스 브리핑",
    thumbnail_url: null,
    url: "https://www.youtube.com/watch?v=mockvid001",
    published_at: `${D}T18:00:00+09:00`,
  },
  {
    id: 2,
    video_id: "mockvid002",
    title: "추경 협상 쟁점 한눈에 정리",
    thumbnail_url: null,
    url: "https://www.youtube.com/watch?v=mockvid002",
    published_at: `${D}T16:30:00+09:00`,
  },
  {
    id: 3,
    video_id: "mockvid003",
    title: "5월 물가 둔화, 우리 지갑은 왜 그대로일까",
    thumbnail_url: null,
    url: "https://www.youtube.com/watch?v=mockvid003",
    published_at: `${D}T14:00:00+09:00`,
  },
  {
    id: 4,
    video_id: "mockvid004",
    title: "국산 AI 반도체, 엔비디아 아성 넘을까",
    thumbnail_url: null,
    url: "https://www.youtube.com/watch?v=mockvid004",
    published_at: `2026-06-10T19:20:00+09:00`,
  },
  {
    id: 5,
    video_id: "mockvid005",
    title: "장마 앞두고 꼭 알아야 할 안전 수칙",
    thumbnail_url: null,
    url: "https://www.youtube.com/watch?v=mockvid005",
    published_at: `2026-06-10T11:00:00+09:00`,
  },
  {
    id: 6,
    video_id: "mockvid006",
    title: "프로야구 선두 다툼, 남은 변수는",
    thumbnail_url: null,
    url: "https://www.youtube.com/watch?v=mockvid006",
    published_at: `2026-06-09T22:10:00+09:00`,
  },
];
